site_name: Form Conductor
site_url: https://formconductor.naingaungluu.me
repo_url: https://github.com/NaingAungLuu/form-conductor
repo_name: form-conductor
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github
  
  logo: assets/logo_mono_transparent.png

nav:
  - Home:
    - Introduction: index.md
    - Installation: installation.md

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/harryluu_96
    
    - icon: fontawesome/brands/github
      link: https://github.com/NaingAungLuu

    - icon: fontawesome/brands/medium
      link: https://medium.com/@naingaungluu

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - social:
      cards: true
      cards_dir: assets/images/social
