name: Android Build

on:
  push:
    branches: [ "master", "develop", "test/**" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
      
        
  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: library-publish
    env:
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
        SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        PGP_KEY_CONTENTS: ${{ secrets.PGP_KEY_CONTENTS }}
        
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - run: 'echo $SIGNING_KEY_ID'
      shell: bash
    
    - run: 'echo $SIGNING_PASSWORD'
      shell: bash
    
    - run: 'echo $SONATYPE_NEXUS_USERNAME'
      shell: bash
      
    - run: 'echo $SONATYPE_NEXUS_PASSWORD'
      shell: bash
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew publishReleasePublicationToMavenCentralRepository
    
  code-coverage-upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Build with Gradle
      run: ./gradlew check koverVerify

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
